using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdSeeDataSpider
{
    public enum E_ERROR_CODE
    {
        OK = 0,
        ERROR,
        ERROR_FILE_NOT_EXIST,
        ERROR_OPEN_FILE_FAILED,
        ERROR_INIT_WEBDRIVER_FAILED,
        ERROR_OPEN_LOGIN_PAGE_FAILED,
        ERROR_USERNAME_OR_PASSWORD_IS_NULL,
        ERROR_NOT_FOUND_ELEMENT_USER_NAME,
        ERROR_NOT_FOUND_ELEMENT_PASSWORD,
        ERROR_NOT_CONFIG_ELEMENT_USER_NAME_OR_PASSWORD,
        ERROR_NOT_FOUND_FORM_BUTTONS_CONTAINER_ELEMENT,
        ERROR_NOT_FOUND_ELEMENT_SUBMIT_BUTTON,
        ERROR_LOGIN_FAILED,
        ERROR_CREATE_HTTP_WEB_REQUEST_FAILED,
        ERROR_GET_RESPONSE_FAILED,
        ERROR_CREATE_RESPONSE_STREAM_READER,
        ERROR_OPEN_DATA_FILE_FAILED,
        ERROR_JSON_DECODE_FAILED,
        ERROR_GET_TABLE_DATA_FAILED,
        ERROR_GET_ANDROID_DATA_FILE_STORE_PATH_FAILED,
        ERROR_JSON_DATA_PARSE_FAILED,
        ERROR_FIELD_STATE_NOT_FOUND,
        ERROR_NOT_FOUND_FIELD_DATA,
        ERROR_JSON_PARSE_AD_LIST_CONTENT_FAILED,
        ERROR_GET_AD_LIST_DATA_FAILED,
        ERROR_JSON_PARSE_AD_DATA_CONTENT_FAILED,
        ERROR_JSON_PARSE_AD_SUMMARY_CONTENT_FAILED,
        ERROR_NOT_FOUND_FIELD_STATE,
        ERROR_SERVER_PROCESS_FAILED,
        ERROR_NOT_FOUND_FIELD_DATA_OBJECT,
        ERROR_NOT_FOUND_FIELD_DATA_OBJECT_AD_COUNT,
        ERROR_NOT_FOUND_FIELD_PAGEID,
        ERROR_NOT_FOUND_FIELD_ACTOR_IMG,
        ERROR_NOT_FOUND_FIELD_ACTOR_CDN_MARK_IMG,
        ERROR_NOT_FOUND_FIELD_ACTOR_CDN_ORIGIN_IMG,
        ERROR_APP_AD_IMAGE_ITEM_IS_NULL,
        ERROR_ANDROID_ID_DATA_FILE_NOT_EXIST,
        ERROR_READ_ANDROID_ID_DATA_FROM_FILE,
        ERROR_USER_NOT_LOGIN
    }
}
