<?php


class ReportConstants
{
    const READ_CAMPAIGN_INSIGHT_ACCOUNT_INTERVAL = 10000;
    const READ_AD_INSIGHT_ACCOUNT_INTERVAL = 10000;

    const REPORT_SPEND_DECIMAL_PRECISION = 3;
    const REPORT_PERCENT_DECIMAL_PRECISION = 2;

    const QUERY_AD_INSIGHT_INTERVAL = 20000;

    const AD_REPORT_LOG_EXTENSION = '.csv';
}